version: '3'

services:
  catalog:
    build: ./catalog
    ports:
      - "4000:8000"
    networks:
      - innerNetwork
    volumes:
      - "./catalog:/app"
      - "./logs/laravel.log:/app/storage/logs/laravel.log"
  order:
    build: ./order
    ports:
      - "4001:8000"
    networks:
      - innerNetwork
    volumes:
      - "./order:/app"
      - "./logs/laravel.log:/app/storage/logs/laravel.log"
  front:
    build: ./front
    ports:
      - "4002:8000"
    networks:
      - innerNetwork
    volumes:
      - "./front:/app"
      - "./logs/laravel.log:/app/storage/logs/laravel.log"
  catalogr:
    build: ./catalogR
    ports:
      - "4003:8000"
    networks:
      - innerNetwork
    volumes:
      - "./catalogR:/app"
      - "./logs/laravel.log:/app/storage/logs/laravel.log"
  orderr:
    build: ./orderR
    ports:
      - "4004:8000"
    networks:
      - innerNetwork
    volumes:
      - "./orderR:/app"  
      - "./logs/laravel.log:/app/storage/logs/laravel.log"    
networks:
  innerNetwork:
